#application.properties:
spring.application.name=demo4
# MySQL settings
spring.datasource.url=jdbc:mysql://localhost:3306/employeeinfydb?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=none
hibernate.show_sql:true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Default port number
server.port=8080

#CREATE TABLE Employee (
#    emp_id BIGINT AUTO_INCREMENT PRIMARY KEY,
#    emp_name VARCHAR(255) NOT NULL,
#    emp_age INT NOT NULL,
#    emp_city VARCHAR(255),
#    email_id VARCHAR(255) NOT NULL UNIQUE,
#    date_of_birth DATE NOT NULL
#);
#
#INSERT INTO Employee (emp_name, emp_age, emp_city, email_id, date_of_birth) 
#VALUES 
#('Amit Kumar', 30, 'Mumbai', 'amit.kumar@example.com', '1994-05-12'),
#('Priya Sharma', 28, 'Delhi', 'priya.sharma@example.com', '1996-08-25'),
#('Rahul Verma', 35, 'Bangalore', 'rahul.verma@example.com', '1989-11-18'),
#('Neha Singh', 27, 'Pune', 'neha.singh@example.com', '1997-03-30'),
#('Rohan Das', 32, 'Kolkata', 'rohan.das@example.com', '1992-07-05');
